src/Entity/Event.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EventRepository")
 */
class Event
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups("event_show")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"event_show", "event_create"})
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"event_show", "event_create"})
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     * @Groups({"event_show", "event_create"})
     */
    private $datetime;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"event_show", "event_create"})
     */
    private $place;

    /**
     * @ORM\Column(type="integer")
     * @Groups({"event_show", "event_create"})
     */
    private $min_age;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\EventType", inversedBy="events")
     * @ORM\JoinColumn(nullable=false)
     *
     */
    private $type;

    /**
     * @ORM\Column(type="integer")
     * @Groups({"event_show", "event_create"})
     */
    private $min_users;

    /**
     * @ORM\Column(type="integer")
     * @Groups({"event_show", "event_create"})
     */
    private $max_users;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="events")
     * @ORM\JoinColumn(nullable=false)
     *  @Groups({"event_show", "event_create"})
     */
    private $organizer;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="events")
     * @Groups({"event_show", "event_create"})
     */
    private $participants;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="event")
     * @Groups({"event_show", "event_create"})
     */
    private $comments;

    /**
     * @ORM\Column(type="array")
     * @Groups({"event_show", "event_create"})
     */
    private $photos = [];

    public function __construct()
    {
        $this->participants = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDatetime(): ?\DateTimeInterface
    {
        return $this->datetime;
    }

    public function setDatetime(\DateTimeInterface $datetime): self
    {
        $this->datetime = $datetime;

        return $this;
    }

    public function getPlace(): ?string
    {
        return $this->place;
    }

    public function setPlace(string $place): self
    {
        $this->place = $place;

        return $this;
    }

    public function getMinAge(): ?int
    {
        return $this->min_age;
    }

    public function setMinAge(int $min_age): self
    {
        $this->min_age = $min_age;

        return $this;
    }

    public function getType(): ?EventType
    {
        return $this->type;
    }

    public function setType(?EventType $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getMinUsers(): ?int
    {
        return $this->min_users;
    }

    public function setMinUsers(int $min_users): self
    {
        $this->min_users = $min_users;

        return $this;
    }

    public function getMaxUsers(): ?int
    {
        return $this->max_users;
    }

    public function setMaxUsers(int $max_users): self
    {
        $this->max_users = $max_users;

        return $this;
    }

    public function getOrganizer(): ?User
    {
        return $this->organizer;
    }

    public function setOrganizer(?User $organizer): self
    {
        $this->organizer = $organizer;

        $this->addParticipant($organizer);

        return $this;

    }

    /**
     * @return Collection|User[]
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(User $participant): self
    {
        if (!$this->participants->contains($participant)) {
            $this->participants[] = $participant;
        }

        return $this;
    }

    public function removeParticipant(User $participant): self
    {
        if ($this->participants->contains($participant)) {
            $this->participants->removeElement($participant);
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setEvent($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getEvent() === $this) {
                $comment->setEvent(null);
            }
        }

        return $this;
    }

    public function getPhotos(): ?array
    {
        return $this->photos;
    }

    public function setPhotos(array $photos): self
    {
        $this->photos = $photos;

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }
}

src/Entity/EventType.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EventTypeRepository")
 */
class EventType
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"eventtype_show"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"eventtype_show", "eventtype_create"})
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Event", mappedBy="type")
     * @Groups({"eventtype_show", "eventtype_create"})
     */
    private $events;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", mappedBy="interests")
     */
    private $users;

    public function __construct()
    {
        $this->events = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Event[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setType($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        if ($this->events->contains($event)) {
            $this->events->removeElement($event);
            // set the owning side to null (unless already changed)
            if ($event->getType() === $this) {
                $event->setType(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return $this->name;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addInterest($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            $user->removeInterest($this);
        }

        return $this;
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('datetime')
            ->add('place')
            ->add('min_age')
            ->add('min_users')
            ->add('max_users')
            ->add('photos')
            ->add('type')
            ->add('organizer')
            ->add('participants')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/Api/EventController.php
<?php


namespace App\Controller\Api;

use App\Entity\Event;
use App\Repository\EventRepository;
use Doctrine\ORM\EntityManagerInterface;
use Nelmio\ApiDocBundle\Annotation\Model;
use Swagger\Annotations as SWG;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;

/**
 * @Route("/event")
 */
class EventController extends AbstractController
{
    /**
     * @Route("/", name="api_event_index", methods={"GET"})
     * @throws \Symfony\Component\Serializer\Exception\ExceptionInterface
     * @throws \ReflectionException
     *
     * @SWG\Tag(name="Event")
     * @SWG\Response(
     *     response=200,
     *     description="Returns Event",
     *     @SWG\Schema(
     *          @Model(type=Event::class, groups={"event_show"})
     *     )
     * )
     *
     * @SWG\Parameter(
     *   name="apikey",
     *   type="string",
     *   required=true,
     *   in="header",
     *   description="auth event's apikey"
     * )
     */
    public function index(EventRepository $eventRepository, SerializerInterface $serializer, Request $request): Response
    {
        $events = $eventRepository->findAll();

        $jsonEvents = $serializer->serialize($events, 'json',['groups' => ['event_show', 'user_show', 'eventtype_show', 'comment_show']]);

        return new JsonResponse($jsonEvents);
    }

    /**
     * @Route("/new", name="api_event_new", methods={"POST"})
     * @throws \Symfony\Component\Serializer\Exception\ExceptionInterface
     *
     * @SWG\Tag(name="Event")
     * @SWG\Response(
     *     response=200,
     *     description="Returns Event",
     *     @SWG\Schema(
     *          @Model(type=Event::class, groups={"event_show"})
     *     )
     * )
     *
     * @SWG\Parameter(
     *   name="apikey",
     *   type="string",
     *   required=true,
     *   in="header",
     *   description="auth user's apikey"
     * )
     *
     * @SWG\Parameter(
     *     name="body",
     *     in="body",
     *     description="Create event schema.",
     *     required=true,
     *     @SWG\Schema(
     *          @Model(type=Event::class, groups={"event_create"})
     *     )
     * )
     */
    public function new(EntityManagerInterface $em, SerializerInterface $serializer, Request $request): Response
    {
        $json = $request->getContent();
        $event = $serializer->deserialize($json, Event::class, 'json', ['groups' => ['event_create']]);
        $em->persist($event);
        $em->flush();
        $jsonEvents = $serializer->serialize($event, 'json', ['groups' => ['event_show', 'user_show', 'eventtype_show', 'comment_show']]);

        return new JsonResponse($jsonEvents);

    }

}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\EventType;
use App\Repository\EventRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/event")
 */
class EventController extends AbstractController
{
    /**
     * @Route("/", name="event_index", methods={"GET"})
     */
    public function index(EventRepository $eventRepository): Response
    {
        return $this->render('event/index.html.twig', [
            'events' => $eventRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="event_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('event_index');
        }

        return $this->render('event/new.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="event_show", methods={"GET"})
     */
    public function show(Event $event): Response
    {
        return $this->render('event/show.html.twig', [
            'event' => $event,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="event_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Event $event): Response
    {
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('event_index');
        }

        return $this->render('event/edit.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="event_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Event $event): Response
    {
        if ($this->isCsrfTokenValid('delete'.$event->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($event);
            $entityManager->flush();
        }

        return $this->redirectToRoute('event_index');
    }
}

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('event_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn">Delete</button>
</form>

templates/event/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Event{% endblock %}

{% block body %}
    <h1>Edit Event</h1>

    {{ include('event/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('event_index') }}">back to list</a>

    {{ include('event/_delete_form.html.twig') }}
{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event index{% endblock %}

{% block body %}
    <h1>Event index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Type</th>
                <th>Description</th>
                <th>Datetime</th>
                <th>Place</th>
                <th>Min_age</th>
                <th>Min_users</th>
                <th>Max_users</th>
                <th>Photos</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for event in events %}
            <tr>
                <td>{{ event.id }}</td>
                <td>{{ event.name }}</td>
                <td>{{ event.type }}</td>
                <td>{{ event.description }}</td>
                <td>{{ event.datetime ? event.datetime|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ event.place }}</td>
                <td>{{ event.minAge }}</td>
                <td>{{ event.minUsers }}</td>
                <td>{{ event.maxUsers }}</td>
                <td>{{ event.photos ? event.photos|join(', ') : '' }}</td>
                <td>
                    <a href="{{ path('event_show', {'id': event.id}) }}">show</a>
                    <a href="{{ path('event_edit', {'id': event.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('event_new') }}">Create new</a>
{% endblock %}

templates/event/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Event{% endblock %}

{% block body %}
    <h1>Create new Event</h1>

    {{ include('event/_form.html.twig') }}

    <a href="{{ path('event_index') }}">back to list</a>
{% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event{% endblock %}

{% block body %}
    <h1>Event</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ event.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ event.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ event.description }}</td>
            </tr>
            <tr>
                <th>Datetime</th>
                <td>{{ event.datetime ? event.datetime|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Place</th>
                <td>{{ event.place }}</td>
            </tr>
            <tr>
                <th>Organizer</th>
                <td>{{ event.organizer }}</td>
            </tr>
            <tr>
                <th>Участники</th>
                <td>{% for user in event.participants %}<a href="{{ path('user_show', {'id': user.id}) }}">{{  user.name }}</a> {% endfor %}</td>

            </tr>
            <tr>
                <th>Min_age</th>
                <td>{{ event.minAge }}</td>
            </tr>
            <tr>
                <th>Min_users</th>
                <td>{{ event.minUsers }}</td>
            </tr>
            <tr>
                <th>Max_users</th>
                <td>{{ event.maxUsers }}</td>
            </tr>
            <tr>
                <th>Photos</th>
                <td>{{ event.photos ? event.photos|join(', ') : '' }}</td>
            </tr>
            <tr>
                <th>Comments</th>
                <td>{{ event.comments ? event.comments|join(', ') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('event_index') }}">back to list</a>

    <a href="{{ path('event_edit', {'id': event.id}) }}">edit</a>

    {{ include('event/_delete_form.html.twig') }}
{% endblock %}