src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"last_name"}, message="There is already an account with this last_name")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups("user_show")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Groups({"user_show", "user_create"})
     */
    private $last_name;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Groups({"user_show", "user_create"})
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"user_show", "user_create"})
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"user_show", "user_create"})
     */
    private $patron_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"user_show", "user_create"})
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"user_show", "user_create"})
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"user_show", "user_create"})
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     * @Groups({"user_show", "user_create"})
     */
    private $rating;



    /**
     * @ORM\Column(type="integer")
     * @Groups({"user_show", "user_create"})
     */
    private $age;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Event", mappedBy="organizer")
     *
     */
    private $events;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Event", mappedBy="participants")
     *
     */
    private $event_participations;


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="user")
     *
     */
    private $comments;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"user_show", "user_create"})
     */
    private $photo;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"user_show", "user_create"})
     */
    private $email;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\EventType", inversedBy="users")
     */
    private $interests;

    public function __construct()
    {
        $this->events = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->interests = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->last_name;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPatronName(): ?string
    {
        return $this->patron_name;
    }

    public function setPatronName(string $patron_name): self
    {
        $this->patron_name = $patron_name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getRating(): ?float
    {
        return $this->rating;
    }

    public function setRating(float $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }

    /**
     * @return Collection|Event[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setOrganizer($this);
        }
        $this->addEventParticipation($event);

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        if ($this->events->contains($event)) {
            $this->events->removeElement($event);
            $event->removeParticipant($this);
            // set the owning side to null (unless already changed)
            if ($event->getOrganizer() === $this) {
                $event->setOrganizer(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Event[]
     */
    public function getEventParticipations() : Collection
    {
        return $this->event_participations;
    }

    public function addEventParticipation(Event $event): self
    {
        if (!$this->event_participations->contains($event)) {
            $this->event_participations[] = $event;
            $event->addParticipant($this);

        }

        return $this;
    }

    public function removeEventParticipation(Event $event): self
    {
        if ($this->event_participations->contains($event)) {
            $this->event_participations->removeElement($event);
            // set the owning side to null (unless already changed)
            if ($event->getParticipants()->contains($this)) {
                $event->removeParticipant($this);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }
    public function __toString()
    {
        return ($this->last_name . " " . $this->name);
    }

    /**
     * @return Collection|EventType[]
     */
    public function getInterests(): Collection
    {
        return $this->interests;
    }

    public function addInterest(EventType $interest): self
    {
        if (!$this->interests->contains($interest)) {
            $this->interests[] = $interest;
        }

        return $this;
    }

    public function removeInterest(EventType $interest): self
    {
        if ($this->interests->contains($interest)) {
            $this->interests->removeElement($interest);
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\Event;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use App\Entity\EventType;
use Symfony\Component\Validator\Constraints\File;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('last_name')
            ->add('name')
            ->add('patron_name')
            ->add('phone')
            ->add('city')
            ->add('description')
            ->add('events',EntityType::class, [
                'label' => 'События',
                'class' => Event::class,
                'expanded' => true,
                'multiple' => true,
                'by_reference' => false
            ])
            ->add('interests', EntityType::class, [
                'label' => 'Интересы',
                'class' => EventType::class,
                'expanded' => true,
                'multiple' => true,
                'by_reference' => false
            ])
            ->add('age')
            ->add('photo', FileType::class, [
                'label' => 'Photo (JPG file)',

                // unmapped means that this field is not associated to any entity property
                'mapped' => false,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false,

                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'application/jpg',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid JPG',
                    ])
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/Api/UserController.php
<?php


namespace App\Controller\Api;

use App\Entity\User;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Nelmio\ApiDocBundle\Annotation\Model;
use Nelmio\ApiDocBundle\Tests\Functional\Controller\FOSRestController;
use phpDocumentor\Reflection\DocBlock\Serializer;
use Swagger\Annotations as SWG;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\AbstractNormalizer;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\SerializerInterface;


/**
 * @Route("/user")
 */

class UserController extends AbstractController
{

    /**
     * @Route("/", name="api_user_index", methods={"GET"})
     * @throws \Symfony\Component\Serializer\Exception\ExceptionInterface
     * @throws \ReflectionException
     *
     * @SWG\Tag(name="User")
     * @SWG\Response(
     *     response=200,
     *     description="Returns User",
     *     @SWG\Schema(
     *          @Model(type=User::class, groups={"user_show"})
     *     )
     * )
     *
     * @SWG\Parameter(
     *   name="apikey",
     *   type="string",
     *   required=true,
     *   in="header",
     *   description="auth user's apikey"
     * )
     */
    public function index(UserRepository $userRepository, SerializerInterface $serializer, Request $request): Response
    {
        $users = $userRepository->findAll();
        $jsonUsers = $serializer->serialize($users, 'json', ['groups' => ['user_show']]);

        return new JsonResponse($jsonUsers);


    }




}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="user_index", methods={"GET"})
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="user_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();
            $userPhoto = $form->get('photo')->getData();
            // this condition is needed because the 'brochure' field is not required
            // so the PDF file must be processed only when a file is uploaded
            if ($userPhoto) {
                $originalFilename = pathinfo($userPhoto->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $userPhoto->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $userPhoto->move(
                        $this->getParameter('brochures_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
            }
            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, User $user): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_delete", methods={"DELETE"})
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index');
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_index') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Last_name</th>
                <th>Name</th>
                <th>Patron_name</th>
                <th>Phone</th>
                <th>City</th>
                <th>Description</th>
                <th>Rating</th>
                <th>Interests</th>
                <th>Age</th>
                <th>Photo</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.lastName }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.patronName }}</td>
                <td>{{ user.phone }}</td>
                <td>{{ user.city }}</td>
                <td>{{ user.description }}</td>
                <td>{{ user.rating }}</td>
                <td>{{ user.interests ? user.interests|join(', ') : '' }}</td>
                <td>{{ user.age }}</td>
                <td>{{ user.photo }}</td>
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="14">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('user_new') }}">Create new</a>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('user_index') }}">back to list</a>
{% endblock %}

templates/user/show.html.twig
<!DOCTYPE html>
<html lang="rus">
<head>
  <meta charset="utf-8">
  <title>AURORA</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <link href={{ absolute_url('../css/bootstrap.css') }} rel="stylesheet">
  <link href={{ absolute_url('../css/main.css') }} rel="stylesheet">
  <link href={{ absolute_url('../css/profile.css') }} rel="stylesheet">
  <link rel="stylesheet" href={{ absolute_url('../font-awesome/css/font-awesome.min.css') }}>
</head>


<body>
    <div class="navbar navbar-light navbar-fixed-top">
        <div class = "navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button " class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            <div class = "sm">
                <a class="navbar-left"><img src={{ absolute_url('../img/logo_m.svg') }} style = "width:90px;height: 114px;"></a>
            </div>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav fixed-bottom navbar-nav navbar-right ">
              
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="profile-container">
        <div class="login_page_logo">
            <div class="login_page_logo_img">
                <p>Личный<br> кабинет
            </div>
        </div>
        <div class="container">
        <div class="row">
            <div class="col-sm-4">
              <img style="width: 50%; float: right;" src={{ absolute_url('../img/unnamed.jpg') }}>
            </div>
            <div class="col-sm-4">
              <p>{{ user.name }}</p>
                <p>{{ user.patronname }}</p>
              <p>{{ user.lastname }}</p>

              <p>{{ user.age }} лет</p>
                {{ user.description }}
                <p></p>
              <p>Интересы: {{ user.interests ? user.interests|join(', ') : '' }}</p>

            </div>
            <div class="col-sm-4">
              <div style="width: 25%; float: left; text-align: center;">
                <img src={{ absolute_url('../img/city.svg') }} style= "width: 100%; margin-left: auto; margin-right: auto;">
                <p>{{ app.user.city }}</p>

              </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div style="text-align: center;">
                    <h3>Мои мероприятия</h3>
                    <p>{{ user.events ? user.events|join(', ') : '' }}</p>
                    <h3>Участие в мероприятиях</h3>
                    <p>{{ user.eventparticipations ? user.eventparticipations|join(', ') : '' }}</p>
                    <img src={{ absolute_url('../img/no_photo.svg') }} style= "width: 50%; margin-left: auto; margin-right: auto;">
                </div>
                
            </div>
        </div>
        </div>

    </div>
    

    <script src={{ absolute_url('../jquery/jquery.js') }}></script>
    <script src={{ absolute_url('../js/bootstrap.min.js') }}></script>
</body>



</html>